/* Export view: bulk CSV/JSON of all activities. Per-activity CSV/JSON/GPX/TCX
   and the original raw file live on each activity's detail page. Downloads
   stream from the local server — nothing leaves your machine. */
const ExportView = (() => {
  let anon = false; // shared by the bulk download buttons; reset on each render

  async function render() {
    anon = false;
    const root = U.el("div");
    root.appendChild(U.el("div", { class: "page-head" }, [
      U.el("div", {}, [
        U.el("h1", { text: "Export" }),
        U.el("div", { class: "sub", text: "Export your library locally. Files are generated by the local server — nothing leaves your machine." }),
      ]),
    ]));

    // Privacy toggle — applies to every export triggered from this page.
    const cb = U.el("input", { type: "checkbox" });
    cb.addEventListener("change", () => { anon = cb.checked; });
    root.appendChild(U.el("div", { class: "card pad", style: "margin-bottom:var(--sp-4)" }, [
      U.el("label", { class: "anon-toggle", title: "Scrub GPS near start/end and strip device & personal data" }, [
        cb, U.el("span", { text: "Anonymize exports — scrub location & sensitive data" }),
      ]),
      U.el("div", { class: "sub", style: "margin-top:6px",
        text: "Non-destructive: applies only to the downloaded copy. Your stored archive stays lossless. Tune the level (privacy radius, GPS fuzzing, date shifting) under the anonymize section of your config." }),
    ]));

    let count = 0;
    try { count = (await API.stats()).count; } catch (_) {}

    root.appendChild(U.el("div", { class: "card pad" }, [
      U.el("h3", { style: "margin-bottom:var(--sp-2)", text: "Bulk export" }),
      U.el("div", { class: "sub", style: "margin-bottom:var(--sp-4)",
        text: `A one-row-per-activity summary of all ${count} activit${count === 1 ? "y" : "ies"}.` }),
      U.el("div", { class: "export-row" }, [
        choice("CSV", "Spreadsheet-friendly summary table", () => dl("csv")),
        choice("JSON", "Structured summary for scripts / analysis", () => dl("json")),
      ]),
    ]));

    root.appendChild(U.el("div", { class: "card pad", style: "margin-top:var(--sp-4)" }, [
      U.el("h3", { style: "margin-bottom:var(--sp-2)", text: "Long-term archive" }),
      U.el("div", { class: "sub", style: "margin-bottom:var(--sp-4)",
        text: "Full-fidelity NDJSON: every activity with its complete time series, laps and all preserved fields (with units). One activity per line — ideal for archiving and later analysis. Your raw files remain the canonical, lossless source." }),
      U.el("div", { class: "export-row" }, [
        choice("NDJSON archive", "Complete dataset, one activity per line", () => dl("ndjson", true)),
        choice("JSON (full)", "Complete dataset as a single JSON array", () => dl("json", true)),
      ]),
    ]));

    root.appendChild(U.el("div", { class: "card pad", style: "margin-top:var(--sp-4)" }, [
      U.el("h3", { style: "margin-bottom:var(--sp-2)", text: "Per-activity export" }),
      U.el("div", { class: "sub", html: "Open any activity from the Dashboard and use the export buttons in its header: <strong>GPX</strong> (universal — Strava, Komoot, …), <strong>TCX</strong> (Garmin Connect / Strava), <strong>CSV/JSON</strong>, or <strong>Original</strong> (the lossless source file). Tick <em>Anonymize</em> there to scrub a single activity." }),
    ]));

    U.setView(root);
  }

  function choice(title, desc, onclick) {
    return U.el("div", { class: "choice", onclick }, [
      U.el("div", { class: "t", text: title }),
      U.el("div", { class: "d", text: desc }),
    ]);
  }

  function dl(fmt, full) {
    U.download(API.bulkExportUrl(fmt, full, anon), `activities.${fmt}`);
    U.toast(`Exporting ${full ? "full archive" : "all activities"} as ${fmt.toUpperCase()}${anon ? " (anonymized)" : ""}…`);
  }

  return { render };
})();
