#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""One-off normalizer: wire the staged research data in ``docs/incoming/`` into the
canonical engine schema served from ``web/content/``.

Two inputs use two shapes (see ``docs/incoming/README.md``):

* **Home** (``home_exercises.engine.json``) is already canonical
  (``views`` -> named poses, ``phases`` with ``from``/``to``, ``cues``,
  ``staticCues``). We merge in the per-exercise library metadata (pattern, tier,
  objects, primary benefit, refs, notes) and ship the union.
* **Tai Chi** (``taichi_movements.json``) uses a self-contained per-phase shape
  (single ``view``; ``phases`` each carry ``durationMs``/``cue``/``pose``). We
  convert it to the canonical schema: ``views.<view>`` is the poses keyed by
  phase name; ``phases`` reference consecutive pose names, looping the last back
  to the first; a hold movement becomes a rise -> hold (``from``==``to``) ->
  lower cycle, exactly like the canonical home holds.

The functions are pure and unit-tested (``tests/test_normalize_incoming.py``);
``main()`` applies them to the staged files. Poses stay 2-D (z omitted = 0).
Run from the repo root: ``python scripts/normalize_incoming.py``.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCOMING = ROOT / "docs" / "incoming"
HOME_OUT = ROOT / "web" / "content" / "home" / "exercises.json"
TAICHI_OUT = ROOT / "web" / "content" / "taichi" / "movements.json"

GROUND_Y = 318

# Library metadata carried over verbatim onto each exercise/movement.
_HOME_META = ("default_object", "regression_object", "progression_lever",
              "primary_benefit", "refs", "red_flags", "notes")
_TAICHI_META = ("level", "focus", "primary_benefit", "refs", "red_flags", "notes")

_HOLD_CUE = "Hold steady and tall — keep breathing slowly; never hold your breath."

_HOME_NOTE = (
    "Data-driven exercise library for the Sports at Home form-model engine. A "
    "figure is named joints (2-D coords in a 240x340 viewBox; the engine accepts "
    "an optional z per joint); a movement is keyframe poses the engine "
    "interpolates between, clocked by tempo. Object glyphs are referenced by id "
    "and drawn by web/js/formModel.js. Each entry also carries library metadata "
    "(pattern, tier, default/regression/progression objects, primary benefit, "
    "evidence refs, notes). Generated by scripts/normalize_incoming.py."
)
_TAICHI_NOTE = (
    "Simplified movement/breathing pacers for the Tai Chi tab, rendered by the "
    "SHARED form-model engine (web/js/formModel.js). Normalized from the "
    "per-phase authoring schema into the canonical views+phases schema by "
    "scripts/normalize_incoming.py. A gentle tempo/breath guide, not instructed "
    "Tai Chi form."
)
_TAICHI_DISCLAIMER = (
    "A simplified breathing-and-tempo pacer — move slowly through a comfortable, "
    "full range. Not a substitute for instructed Tai Chi form. Stop for chest "
    "pain, breathlessness, dizziness, or new joint pain."
)


def merge_home_exercise(engine: dict, meta: dict) -> dict:
    """Merge a canonical engine entry with its library metadata (pure)."""
    if meta.get("pattern") and engine.get("pattern") and meta["pattern"] != engine["pattern"]:
        raise ValueError(f"{engine['id']}: pattern mismatch {engine['pattern']} != {meta['pattern']}")
    if meta.get("tier") and engine.get("tier") and meta["tier"] != engine["tier"]:
        raise ValueError(f"{engine['id']}: tier mismatch {engine['tier']} != {meta['tier']}")
    out = dict(engine)
    for key in _HOME_META:
        if key in meta:
            out[key] = meta[key]
    return out


def _static_labels_3(labels: list | None) -> list | None:
    """Normalize authoring labels to the 3 captions the static fallback shows."""
    if not labels:
        return None
    if len(labels) == 2:
        return [labels[0], labels[1], labels[0]]
    return labels[:3] if len(labels) > 3 else labels


def normalize_taichi_movement(mv: dict, meta: dict | None = None) -> dict:
    """Convert a per-phase Tai Chi movement to the canonical engine schema (pure).

    Non-hold: 1:1 phases looping the last pose back to the first (each phase
    animates *into* its named pose). Hold: a rise -> hold(from==to) -> lower cycle
    built from the settle (first) and hold (last) poses, matching canonical home
    holds so the lift is animated and the hold counts down for ``holdMs``.
    """
    view = mv["view"]
    phases_in = mv["phases"]
    names = [p["name"] for p in phases_in]
    is_hold = bool(mv.get("isHold"))
    poses = {p["name"]: p["pose"] for p in phases_in}

    cues: dict[str, str] = {p["name"]: p["cue"] for p in phases_in}

    if is_hold and len(phases_in) == 2:
        settle, hold = phases_in[0], phases_in[1]
        hold_ms = int(mv.get("holdMs") or hold["durationMs"])
        out_phases = [
            {"name": hold["name"], "dur": int(hold["durationMs"]),
             "from": settle["name"], "to": hold["name"]},
            {"name": "Hold", "dur": hold_ms,
             "from": hold["name"], "to": hold["name"], "isHold": True},
            {"name": settle["name"], "dur": int(settle["durationMs"]),
             "from": hold["name"], "to": settle["name"]},
        ]
        cues["Hold"] = _HOLD_CUE
        static_cues = [hold["cue"], _HOLD_CUE, settle["cue"]]
    else:
        out_phases = []
        for i, p in enumerate(phases_in):
            prev = names[i - 1]  # i-1 == -1 loops to the last phase
            phase = {"name": p["name"], "dur": int(p["durationMs"]),
                     "from": prev, "to": p["name"]}
            if is_hold and i == len(phases_in) - 1:
                phase["from"] = p["name"]  # keep the hold phase from==to
                phase["dur"] = int(mv.get("holdMs") or p["durationMs"])
                phase["isHold"] = True
            out_phases.append(phase)
        static_cues = [p["cue"] for p in phases_in]

    obj = {"side": None, "front": None}
    obj[view] = mv.get("object")

    out: dict = {
        "id": mv["id"],
        "name": mv["name"],
        "object": obj,
        "views": {view: poses},
        "phases": out_phases,
        "cues": cues,
        "staticCues": static_cues,
    }
    labels = _static_labels_3(mv.get("staticLabels"))
    if labels:
        out["staticLabels"] = labels
    if mv.get("targetReps"):
        out["targetReps"] = mv["targetReps"]
    if is_hold:
        out["isHold"] = True
        if mv.get("holdMs"):
            out["holdMs"] = mv["holdMs"]
    if meta:
        for key in _TAICHI_META:
            if key in meta:
                out[key] = meta[key]
    return out


def build_home() -> dict:
    engine = json.loads((INCOMING / "home_exercises.engine.json").read_text("utf-8"))
    library = {x["id"]: x for x in json.loads((INCOMING / "home_exercises.library.json").read_text("utf-8"))}
    exercises = [merge_home_exercise(e, library.get(e["id"], {})) for e in engine]
    return {"_note": _HOME_NOTE, "ground_y": GROUND_Y, "exercises": exercises}


def build_taichi() -> dict:
    movements = json.loads((INCOMING / "taichi_movements.json").read_text("utf-8"))
    library = {x["id"]: x for x in json.loads((INCOMING / "taichi_library.json").read_text("utf-8"))}
    norm = [normalize_taichi_movement(m, library.get(m["id"])) for m in movements]
    return {"_note": _TAICHI_NOTE, "ground_y": GROUND_Y,
            "disclaimer": _TAICHI_DISCLAIMER, "movements": norm}


def main() -> None:
    home = build_home()
    taichi = build_taichi()
    HOME_OUT.write_text(json.dumps(home, indent=2, ensure_ascii=False) + "\n", "utf-8")
    TAICHI_OUT.write_text(json.dumps(taichi, indent=2, ensure_ascii=False) + "\n", "utf-8")
    print(f"wrote {HOME_OUT.relative_to(ROOT)} ({len(home['exercises'])} exercises)")
    print(f"wrote {TAICHI_OUT.relative_to(ROOT)} ({len(taichi['movements'])} movements)")


if __name__ == "__main__":
    main()
